// This file will be auto-generated by Supabase CLI, but we'll define basic types for now
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          name: string
          location: string | null
          address: string | null
          latitude: number | null
          longitude: number | null
          avatar_url: string | null
          phone_number: string | null
          start_date: string
          user_plan: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          name: string
          location?: string | null
          address?: string | null
          latitude?: number | null
          longitude?: number | null
          avatar_url?: string | null
          phone_number?: string | null
          start_date?: string
          user_plan?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          location?: string | null
          address?: string | null
          latitude?: number | null
          longitude?: number | null
          avatar_url?: string | null
          phone_number?: string | null
          start_date?: string
          user_plan?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      walk_completions: {
        Row: {
          id: string
          user_id: string
          week_number: number
          day_of_week: string
          distance_km: number
          completed_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          week_number: number
          day_of_week: string
          distance_km: number
          completed_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          week_number?: number
          day_of_week?: string
          distance_km?: number
          completed_at?: string
          created_at?: string
        }
      }
      phase_unlocks: {
        Row: {
          id: string
          user_id: string
          phase_number: number
          unlocked_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          phase_number: number
          unlocked_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          phase_number?: number
          unlocked_at?: string
          created_at?: string
        }
      }
      phase_completions: {
        Row: {
          id: string
          user_id: string
          phase_number: number
          completed_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          phase_number: number
          completed_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          phase_number?: number
          completed_at?: string
          created_at?: string
        }
      }
      teams: {
        Row: {
          id: string
          name: string | null
          created_by: string
          max_members: number
          whatsapp_link: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name?: string | null
          created_by: string
          max_members?: number
          whatsapp_link?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string | null
          created_by?: string
          max_members?: number
          whatsapp_link?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      team_members: {
        Row: {
          id: string
          team_id: string
          user_id: string
          role: 'leader' | 'member'
          joined_at: string
        }
        Insert: {
          id?: string
          team_id: string
          user_id: string
          role?: 'leader' | 'member'
          joined_at?: string
        }
        Update: {
          id?: string
          team_id?: string
          user_id?: string
          role?: 'leader' | 'member'
          joined_at?: string
        }
      }
      team_invitations: {
        Row: {
          id: string
          team_id: string
          invited_by: string
          invited_user_id: string
          status: 'pending' | 'accepted' | 'declined'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          team_id: string
          invited_by: string
          invited_user_id: string
          status?: 'pending' | 'accepted' | 'declined'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          team_id?: string
          invited_by?: string
          invited_user_id?: string
          status?: 'pending' | 'accepted' | 'declined'
          created_at?: string
          updated_at?: string
        }
      }
      gallery_images: {
        Row: {
          id: string
          user_id: string
          album_month: number
          image_url: string
          caption: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          album_month: number
          image_url: string
          caption?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          album_month?: number
          image_url?: string
          caption?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      gallery_likes: {
        Row: {
          id: string
          image_id: string
          user_id: string
          created_at: string
        }
        Insert: {
          id?: string
          image_id: string
          user_id: string
          created_at?: string
        }
        Update: {
          id?: string
          image_id?: string
          user_id?: string
          created_at?: string
        }
      }
      gallery_comments: {
        Row: {
          id: string
          image_id: string
          user_id: string
          content: string
          created_at: string
        }
        Insert: {
          id?: string
          image_id: string
          user_id: string
          content: string
          created_at?: string
        }
        Update: {
          id?: string
          image_id?: string
          user_id?: string
          content?: string
          created_at?: string
        }
      }
      trail_completions: {
        Row: {
          id: string
          user_id: string
          trail_id: string
          completed_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          trail_id: string
          completed_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          trail_id?: string
          completed_at?: string
          created_at?: string
        }
      }
      book_completions: {
        Row: {
          id: string
          user_id: string
          book_id: string
          completed_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          book_id: string
          completed_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          book_id?: string
          completed_at?: string
          created_at?: string
        }
      }
      magnolias_hikes_completions: {
        Row: {
          id: string
          user_id: string
          hike_id: string
          completed_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          hike_id: string
          completed_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          hike_id?: string
          completed_at?: string
          created_at?: string
        }
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          status: 'pending' | 'active' | 'canceled' | 'expired' | 'past_due'
          current_period_start: string
          current_period_end: string
          cancel_at_period_end: boolean
          plan_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          status?: 'pending' | 'active' | 'canceled' | 'expired' | 'past_due'
          current_period_start?: string
          current_period_end?: string
          cancel_at_period_end?: boolean
          plan_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          status?: 'pending' | 'active' | 'canceled' | 'expired' | 'past_due'
          current_period_start?: string
          current_period_end?: string
          cancel_at_period_end?: boolean
          plan_id?: string
          created_at?: string
          updated_at?: string
        }
      }
    }
    Functions: {
      find_users_within_radius: {
        Args: {
          user_lat: number
          user_lng: number
          radius_miles?: number
        }
        Returns: {
          id: string
          name: string
          location: string | null
          address: string | null
          latitude: number | null
          longitude: number | null
          distance_miles: number
        }[]
      }
    }
  }
}

