export interface Product {
  id: string;
  title: string;
  description: string;
  category: string;
  amazonLink?: string; // For single link products
  amazonLinkMen?: string; // For dual-link products
  amazonLinkWomen?: string; // For dual-link products
}

export const products: Product[] = [
  {
    id: 'salomon-x-ultra-4',
    title: 'Salomon X Ultra 4 Mid GTX',
    description: 'La bota de media caña más equilibrada; protege el tobillo y cuenta con membrana Gore-Tex para mantener la impermeabilidad.',
    category: 'Calzado Técnico',
    amazonLinkMen: 'https://amzn.to/4bbvMVV',
    amazonLinkWomen: 'https://amzn.to/4aFUNZb',
  },
  {
    id: 'columbia-woodburn-ii',
    title: 'Columbia Woodburn II Waterproof',
    description: 'Una opción ligera, cómoda y de alto rendimiento, ideal para quienes buscan agilidad en distancias de 100 km.',
    category: 'Calzado Técnico',
    amazonLink: 'https://amzn.to/3LsPimr',
  },
  {
    id: 'osprey-stratos-36',
    title: 'Osprey Stratos 36 / Sirrus 36',
    description: 'El tamaño perfecto para rutas de varios días. Su sistema de espalda ventilada es líder en el mercado por su comodidad.',
    category: 'Mochila y Protección',
    amazonLink: 'https://amzn.to/492pmaf',
  },
  {
    id: 'poncho-altus-atmospheric',
    title: 'Poncho Altus Atmospheric J30',
    description: 'El estándar de oro para el peregrino. Cubre al usuario y la mochila, ofreciendo una alta resistencia al viento y la lluvia.',
    category: 'Mochila y Protección',
    amazonLink: 'https://amzn.to/49zQoGe',
  },
  {
    id: 'funda-lluvia-mochila',
    title: 'Funda de lluvia para mochila',
    description: 'Protección adicional imprescindible para mantener tu equipo seco dentro de la mochila en cualquier circunstancia.',
    category: 'Mochila y Protección',
    amazonLink: 'https://amzn.to/494yECN',
  },
  {
    id: 'danish-endurance-lana',
    title: 'Danish Endurance (Lana Merina)',
    description: 'Calcetines diseñados para regular la temperatura y gestionar la humedad, reduciendo drásticamente el riesgo de ampollas.',
    category: 'Cuidado del Pie',
    amazonLink: 'https://amzn.to/4jiWOg2',
  },
  {
    id: 'injinji-liner-crew',
    title: 'Injinji Liner Crew NuWool',
    description: 'Calcetines de dedos para usar bajo el calcetín principal; eliminan el roce entre los dedos y previenen lesiones en la piel.',
    category: 'Cuidado del Pie',
    amazonLink: 'https://amzn.to/491sR0G',
  },
  {
    id: 'compeed-ampollas',
    title: 'Compeed Ampollas Mixto',
    description: 'Parches hidrocoloides de alta adherencia, esenciales para el alivio inmediato y la curación de rozaduras en ruta.',
    category: 'Cuidado del Pie',
    amazonLink: 'https://amzn.to/3YT8lcE',
  },
  {
    id: 'camiseta-ultrasport-merin',
    title: 'Camiseta térmica Ultrasport Merin',
    description: 'Capa base con excelente relación calidad-precio, diseñada para mantener la temperatura corporal sin añadir volumen.',
    category: 'Ropa Técnica y Capas',
    amazonLink: 'https://amzn.to/49Bs9Hy',
  },
  {
    id: 'camiseta-helly-hansen-lifa',
    title: 'Camiseta térmica Helly Hansen LIFA Merino',
    description: 'Prenda de alta gama que combina lana merina con tecnología de secado rápido para climas variables.',
    category: 'Ropa Técnica y Capas',
    amazonLink: 'https://amzn.to/3N1zK9N',
  },
  {
    id: 'chaqueta-helly-hansen-seven',
    title: 'Chaqueta Helly Hansen Seven J',
    description: 'Chubasquero clásico, totalmente impermeable y cortavientos; una barrera fiable contra los elementos.',
    category: 'Ropa Técnica y Capas',
    amazonLink: 'https://amzn.to/3MYxIY0',
  },
  {
    id: 'chaqueta-north-face-resolve',
    title: 'Chaqueta The North Face Resolve 2',
    description: 'Prenda robusta con costuras selladas, diseñada para caminatas largas bajo condiciones de lluvia intensa.',
    category: 'Ropa Técnica y Capas',
    amazonLink: 'https://amzn.to/49kcRWE',
  },
  {
    id: 'chaqueta-columbia-watertight',
    title: 'Chaqueta Columbia Watertight II',
    description: 'Opción ligera y altamente compactable que se guarda en su propio bolsillo, ideal para optimizar el espacio.',
    category: 'Ropa Técnica y Capas',
    amazonLink: 'https://amzn.to/4azYks2',
  },
  {
    id: 'pantalones-izas-ample',
    title: 'Pantalones Izas Ample',
    description: 'Pantalones elásticos de secado rápido y alta resistencia a las rozaduras, diseñados para el movimiento constante.',
    category: 'Ropa Técnica y Capas',
    amazonLink: 'https://amzn.to/49BnSnx',
  },
  {
    id: 'pantalones-columbia-silver-ridge',
    title: 'Pantalones Columbia Silver Ridge II',
    description: 'Diseño convertible que permite adaptarse rápidamente a los cambios de temperatura durante la jornada.',
    category: 'Ropa Técnica y Capas',
    amazonLink: 'https://amzn.to/4pvB0zC',
  },
  {
    id: 'pantalones-helikon-tactical',
    title: 'Pantalones Helikon-Tex Outdoor Tactical',
    description: 'Durabilidad extrema con múltiples bolsillos técnicos para mantener documentos y dispositivos siempre a mano.',
    category: 'Ropa Técnica y Capas',
    amazonLink: 'https://amzn.to/3YQ9EJl',
  },
  {
    id: 'glymnis-bastones-plegables',
    title: 'Glymnis Bastones Plegables',
    description: 'Fabricados en Aluminio 7075; son ligeros, resistentes y reducen significativamente el impacto en las rodillas.',
    category: 'Equipo de Apoyo y Descanso',
    amazonLink: 'https://amzn.to/4pkqPOc',
  },
  {
    id: 'saco-sabana-sea-to-summit',
    title: 'Saco Sábana Sea to Summit',
    description: 'Añade una capa de higiene y confort térmico en los albergues; ligero y esencial para cualquier peregrino.',
    category: 'Equipo de Apoyo y Descanso',
    amazonLink: 'https://amzn.to/4bcydrd',
  },
  {
    id: 'tapones-biotap',
    title: 'Tapones para oídos BioTap',
    description: 'Protección indispensable contra el ruido ambiental para garantizar un descanso reparador en alojamientos compartidos.',
    category: 'Equipo de Apoyo y Descanso',
    amazonLink: 'https://amzn.to/4qDVffs',
  },
  {
    id: 'botella-lifestraw-go',
    title: 'Botella LifeStraw Go',
    description: 'Incluye filtro de agua integrado de alta tecnología, permitiendo rellenar de forma segura en diversas fuentes de agua.',
    category: 'Hidratación',
    amazonLink: 'https://amzn.to/4pnGUmd',
  },
  {
    id: 'bolsa-hidratacion-waterbladder',
    title: 'Bolsa de hidratación (WaterBladder)',
    description: 'Sistema que permite beber mediante un tubo sin detener la marcha, facilitando una hidratación constante.',
    category: 'Hidratación',
    amazonLink: 'https://amzn.to/3Nou4qi',
  },
  {
    id: 'botella-plegable-nomader',
    title: 'Botella plegable Nomader',
    description: 'Extremadamente resistente y flexible; se enrolla cuando está vacía para maximizar el espacio en la mochila.',
    category: 'Hidratación',
    amazonLink: 'https://amzn.to/3Lghd99',
  },
  {
    id: 'bateria-anker-powercore',
    title: 'Batería Anker PowerCore',
    description: 'Batería externa de alta capacidad para asegurar que tus dispositivos de navegación y comunicación nunca se agoten.',
    category: 'Tecnología y Seguridad',
    amazonLink: 'https://amzn.to/4q3yv8I',
  },
  {
    id: 'cargador-multipuerto-usb',
    title: 'Cargador multi-puerto USB',
    description: 'Permite cargar múltiples dispositivos simultáneamente usando una sola toma de corriente en los albergues.',
    category: 'Tecnología y Seguridad',
    amazonLink: 'https://amzn.to/4sdw0Sy',
  },
  {
    id: 'rinonera-seguridad',
    title: 'Riñonera de seguridad',
    description: 'Bolso compacto para mantener siempre contigo el dinero, documentos de identidad y la credencial del peregrino.',
    category: 'Tecnología y Seguridad',
    amazonLink: 'https://amzn.to/4jjMOTP',
  },
  {
    id: 'navaja-victorinox',
    title: 'Navaja Victorinox',
    description: 'Herramienta multiusos de alta calidad, útil para la preparación de alimentos y pequeñas reparaciones de emergencia.',
    category: 'Tecnología y Seguridad',
    amazonLink: 'https://amzn.to/4jm75YQ',
  },
  {
    id: 'botiquin-basico',
    title: 'Botiquín básico',
    description: 'Incluye vaselina y desinfectante, elementos clave para prevenir la fricción y tratar pequeñas heridas de forma inmediata.',
    category: 'Salud e Higiene',
    amazonLink: 'https://amzn.to/4bdNWX2',
  },
  {
    id: 'pinzas-lavanderia',
    title: 'Pinzas de lavandería',
    description: 'Esenciales para gestionar tu colada en los albergues o para secar prendas sobre la mochila durante la caminata.',
    category: 'Salud e Higiene',
    amazonLink: 'https://amzn.to/49C9wDu',
  },
  {
    id: 'protector-solar-balsamo',
    title: 'Protector solar y bálsamo labial',
    description: 'Protección contra la radiación UV y el viento, previniendo quemaduras incluso en días nublados.',
    category: 'Salud e Higiene',
    amazonLink: 'https://amzn.to/4jvt2VK',
  },
  {
    id: 'barritas-rxbar',
    title: 'Barritas RXBAR',
    description: 'Nutrición limpia con ingredientes naturales; densas en energía y resistentes a los cambios de presión en viajes internacionales.',
    category: 'Nutrición en Ruta',
    amazonLink: 'https://amzn.to/4bdObRW',
  },
  {
    id: 'barritas-clif-bar',
    title: 'Barritas CLIF Bar',
    description: 'Fuente de carbohidratos de liberación prolongada, diseñadas para mantener los niveles de energía en rutas de resistencia.',
    category: 'Nutrición en Ruta',
    amazonLink: 'https://amzn.to/49ibpnk',
  },
  {
    id: 'mezcla-frutos-secos',
    title: 'Mezcla de Frutos Secos',
    description: 'Snack equilibrado en grasas saludables y sales, presentado en bolsas individuales selladas para mayor comodidad.',
    category: 'Nutrición en Ruta',
    amazonLink: 'https://amzn.to/49dNZQ5',
  },
  {
    id: 'electrolitos-nuun',
    title: 'Electrolitos Nuun',
    description: 'Pastillas efervescentes que ayudan a mantener el equilibrio mineral y prevenir calambres musculares sin azúcares añadidos.',
    category: 'Nutrición en Ruta',
    amazonLink: 'https://amzn.to/4bg1vW3',
  },
];

